import piarm
import random
import time
from time import sleep

my_robot = piarm.PiArm()
try:
    my_robot.connect("/dev/ttyUSB0")
except:
    print('Error connecting to PiArm')
    exit()
    
if my_robot.alive:
    print('PiArm Connected!')
    if True:
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 0)
        my_robot.servoWrite(3, 0)
        my_robot.servoWrite(4, 0)
        my_robot.servoWrite(5, 0)
        my_robot.servoWrite(6, 0)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 0)
        my_robot.servoWrite(3, 0)
        my_robot.servoWrite(4, 0)
        my_robot.servoWrite(5, 0)
        my_robot.servoWrite(6, 402)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 0)
        my_robot.servoWrite(3, 0)
        my_robot.servoWrite(4, 0)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 402)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 0)
        my_robot.servoWrite(3, 800)
        my_robot.servoWrite(4, 0)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 402)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 700)
        my_robot.servoWrite(4, 200, 999)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 402)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 800)
        my_robot.servoWrite(4, 200)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 800)
        my_robot.servoWrite(4, 400, 999)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        time.sleep(2)
        my_robot.servoWrite(1, 600)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 800)
        my_robot.servoWrite(4, 400, 999)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        time.sleep(2)
        my_robot.servoWrite(1, 600)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 700, 999)
        my_robot.servoWrite(4, 200, 999)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        time.sleep(2)
        my_robot.servoWrite(1, 600)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 700)
        my_robot.servoWrite(4, 200)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        time.sleep(2)
        my_robot.servoWrite(1, 200)
        my_robot.servoWrite(2, 100)
        my_robot.servoWrite(3, 700)
        my_robot.servoWrite(4, 200)
        my_robot.servoWrite(5, 500)
        my_robot.servoWrite(6, 400)
        sleep(10)
        
        
        
        

        
        